sonar.projectName=external-config-sbt-2.0
sonar.projectKey=external-config-sbt-2.0
sonar.projectVersion=0
sonar.sources=src/main/scala
sonar.tests=src/test/scala
sonar.sourceEncoding=UTF-8
sonar.scala.version=3.8.4
sonar.scala.scoverage.reportPath=target/out/jvm/scala-3.8.4/external-config-sbt-2-0/scoverage-report/scoverage.xml
sonar.scala.scapegoat.reportPath=target/out/jvm/scala-3.8.4/external-config-sbt-2-0/scapegoat-report/scapegoat.xml
